version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
      - NGINX_HOST=oujun.work
      - NGINX_PORT=80
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/www/html:/usr/share/nginx/html
      - ./letsencrypt/etc/:/etc/letsencrypt/
      - /dev/shm/:/dev/shm/
  xray:
    image: teddysun/xray:latest
    container_name: xray
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/xray/VLESS-GRPC.json:/etc/xray/config.json:ro
      - ./letsencrypt/etc/:/etc/letsencrypt
      - /dev/shm/:/dev/shm/
    restart: always
